name: CI

on:
  push:
    branches: [ main ]
    paths:
      - '**/*.porth'
      - '!example/Template/**'
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup env
        run: |
          sudo apt update
          sudo apt install wabt binaryen fasm
      
      - name: Download WASM4
        uses: robinraju/release-downloader@v1.3
        with:
          latest: true
          repository: aduros/wasm4
          fileName: w4-linux.zip
          
      - name: Unzip WASM4
        run: |
          unzip w4-linux.zip
          rm -f w4-linux.zip
          
      - name: Cache porth
        id: cache-porth
        uses: actions/cache@v3
        with:
          path: |
            porth/porth
            porth/std
          key: ${{ runner.os }}-porth-lib
          
      - name: Bootstrap Porth
        if: steps.cache-porth.outputs.cache-hit != 'true'
        run: |
          git clone https://gitlab.com/tsoding/porth.git
          cd porth
          fasm -m 524288 ./bootstrap/porth-linux-x86_64.fasm
          chmod +x ./bootstrap/porth-linux-x86_64
          ./bootstrap/porth-linux-x86_64 com ./porth.porth
          ./porth com ./porth.porth
      
      - name: Build 4orth
        run: ./porth/porth -I ./porth/std com 4orth.porth
        
      - name: Test Compilation
        run: ./4orth -I ./porth/std com -b -opt -wat ./example/tictactoe.porth
      
      - name: Persist build 
        uses: actions/upload-artifact@v3
        with:
          name: 4orth
          path: |
            4orth
            porth/std/core.porth
            std/
      
      - name: Test html Bundle 
        run:  ./w4 bundle ./example/tictactoe.wasm --title "Ultimate Tic Tac Toe" --html index.html
      
      - name: Persit Html
        uses: actions/upload-artifact@v3
        with:
          name: index
          path: index.html

  deploy-page:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: index
      
      - name: Makedir
        run:  mkdir pages && mv index.html pages
      
      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: pages
